name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Set production env
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - run: yes | sdkmanager --licenses

      - run: npm ci --omit=dev

      - run: echo "EXPO_NO_DAEMON=1" >> $GITHUB_ENV

      - run: npx expo prebuild -p android --non-interactive

      - run: chmod +x android/gradlew

      - run: cd android && ./gradlew assembleRelease -PnewArchEnabled=false

      - name: Rename APK
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          mv android/app/build/outputs/apk/release/app-release.apk gurbani-247-$VERSION.apk

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Gurbani 24/7 Build v1.0.${{ github.run_number }}
          files: gurbani-247-$VERSION-v1.0.${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}